### ISSUE TITLE
Scroll snapping

### ISSUE THREAD

**Issue by JKamue** [DaRealRoyal/tmr_web2#3]
https://codepen.io/tutsplus/pen/qpJYaK

Damit man beim Scrollen nicht mehr zwischen 2 Screens hängen bleiben kann

**Comment by nalsai** [comment]
Bei dem Codepen ist es etwas irritierend, dass es so lange braucht, um zu einem Bereich zu snappen. Das scheint, durch CSS scroll snapping zu passieren. Dann würde ich es aber direkt per CSS einbauen, ohne unnötige JS Library.
[https://css-tricks.com/practical-css-scroll-snapping/](https://css-tricks.com/practical-css-scroll-snapping/)

**Comment by nalsai** [comment]
Implementing scroll snapping breaks the JavaScript scroll location detection of the theme, which is used for the sidebar and animations. Also, I do not think it feels good to use a site with scroll snapping.

See: https://github.com/DaRealRoyal/TacticalWebsite/tree/scroll-snap, live at https://scroll-snap.tacticalwebsite.pages.dev/ (you may need to reload with Ctrl + F5 to refresh the linked styles and scripts)

An alternative implementation would be to remove the wrapper container and use the body for scrolling, but that would also require somewhat major changes to the css and js of the theme.

**Comment by JKamue** [comment]
3 Jahre später??!
